### ISSUE TITLE
Setup code coverage in CI

### ISSUE THREAD

**Issue by taiki-e** [openrr/grid_map#33]
Basically, the same configuration as used in `k` is preferred, but we would like to use the Codecov format instead of Lcov (like https://github.com/openrr/openrr/commit/6f5f76c69e1e6cca7da823455f86d2f3ef4196d0 did).

https://github.com/openrr/k/blob/2a0d3525318810745fb999bf1a14322e422d5b3e/.github/workflows/ci.yml#L98

**Comment by H1rono** [comment]
@taiki-e Should we split the `coverage` job and the current `build` job?

**Comment by taiki-e** [comment]
Yeah, it's better to add it as another job.
